### PR TITLE
fixes issue where wrong credentials would be returned after signing into github

### LINKED ISSUE #179: UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Unauthorized
Steps to reproduce: 

1. Login with wrong credentials
2. Login with correct credentials
3. Application fails when trying to get repos for a user. 

`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Unauthorized`

### PR DESCRIPTION
**Pull request by jackcmeyer**
fixes #179 

* adds return statement to recursive `signInToGithub()` call

### CODE REVIEW

File: src/cli.js [hunk 1]
```diff
@@ -183,6 +183,7 @@ export async function run(configFile, logFile) {
   try {
     const credentials = await signInToThirdPartyTools(configurations.toolingConfigurations);
     configurations.credentials = credentials;
+    console.log(configurations.credentials);
```
Comment (clarkerican) [inline src/cli.js]: You're going to want to delete this
