### PR TITLE
fixes issue where an UnhandledPromiseRejectionWarning would be thrown…

### LINKED ISSUE #140: UnhandledPromiseRejectionWarning when creating project without GitHub
When a user does not select GitHub as an option, there project generates succesfully, but then a message ```(node:4420) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'url' of undefined``` appears

### PR DESCRIPTION
**Pull request by jackcmeyer**
fixes #140 

* fixes an issue where an unhandled promise rejection warning would be thrown if the user did not use github
* the issue was that the finally block, deleteGitHubToken was looking for credentials, but they were not necessarily there since they user did not have to enter them. 
* added a check to make sure they were there before calling the function

### CODE REVIEW

File: src/cli.js [hunk 1]
```diff
@@ -315,10 +315,18 @@ export default async function run(tyr) {
...
     log.error('Failed to generate your project!', err);
   } finally {
-    await deleteGitHubToken(
-      configs.credentials.github.url,
-      configs.credentials.github.username,
-      configs.credentials.github.password
-    );
+    if (typeof configs.credentials.github !== 'undefined') {
+      try {
+        await
```
Comment (enclark) [inline src/cli.js]: Why are we awaiting this? Wouldn't it be better to make it async and then just call .catch on the promise?

Comment (enclark) [reply src/cli.js]: He said that it might hang so we want to await it since it is the last thing we will have to do in the program before it exits
