### PR TITLE
Make Heroku Names Compliant

### LINKED ISSUE #135: Uncaught name format exception
https://github.com/NathanDeGraafTest/Name-must-start-with-a-letter-and-can-only-contain-lowercase-letters-numbers-and-dashes.

Result of using the name Nathan3. 

This brings up a curious point, to make sure we are in compliance with third party names.

### PR DESCRIPTION
**Pull request by jackcmeyer**
closes #135 

* adds validation so projects can only be 20 characters long (needed since heroku name has to be less than 29 characters and we will append 8 characters in case of duplication). 
* created functionality to make all letters lowercase and remove special characters for herokuAppName
* adds relevant tests

### CODE REVIEW

File: src/utils/heroku-name-util.js [hunk 1]
```diff
@@ -0,0 +1,8 @@
+/* eslint-disable import/prefer-default-export */
+
+export function makeHerokuAppNameCompliant(originalHerokuAppName) {
```
Comment (enclark) [inline src/utils/heroku-name-util.js]: Can this file maybe be heroku util so it's less specific to the function?

File: test/heroku-name-util.test.js [hunk 2]
```diff
@@ -0,0 +1,14 @@
+import assert from 'assert';
+import {makeHerokuAppNameCompliant} from "../dist/utils/heroku-name-util";
```
Comment (enclark) [inline test/heroku-name-util.test.js]: Add spaces around the variable to be consistent with the linter

File: test/heroku-name-util.test.js [hunk 3]
```diff
@@ -0,0 +1,14 @@
...
+
+describe('Heroku Name Util', () => {
```
Comment (enclark) [inline test/heroku-name-util.test.js]: If the file name changes, this should be changed
